#!/bin/bash

set -euo pipefail

usage() {
  cat <<-END
usage: build [ -k { corne_min | ferris_sweep } ] [ -f | -d ]
       build [ -i | -s ]

    -d             draw keymap
    -f             build firmware
    -k <keyboard>  select keyboard
    -i             build docker image
    -s             get an interactive shell in the docker container

END
}

DOCKER_MOUNTS=(
  --mount type=bind,src=./config,dst=/app/config,readonly
  --mount type=bind,src=./firmware,dst=/app/out/firmware,bind-create-src
  --mount type=bind,src=./img,dst=/app/out/img
)

mode="f"
keyboards="corne_min ferris_sweep"

while getopts ":dfk:is" opt; do
  case ${opt} in
    d|f|i|s) mode=${opt} ;;

    k)
      case ${OPTARG} in
        corne_min|ferris_sweep)
          keyboards=${OPTARG}
          ;;
        *) usage; exit 1 ;;
      esac
      ;;

    h) usage; exit ;;
    *) usage; exit 1 ;;
  esac
done

case ${mode} in
  d)
    for keyboard in ${keyboards}; do
      case ${keyboard} in
        corne_min)
          docker run --rm "${DOCKER_MOUNTS[@]}" --name draw zmk-config draw -k corne_min -d zmk/app/dts/layouts/foostan/corne/6column.dtsi
          open img/corne_min.svg
          ;;
        ferris_sweep)
          docker run --rm "${DOCKER_MOUNTS[@]}" --name draw zmk-config draw -k cradio
          open img/cradio.svg
          ;;
      esac
    done
    ;;

  f)

    for keyboard in ${keyboards}; do
      case ${keyboard} in
        corne_min)
          docker run --rm "${DOCKER_MOUNTS[@]}" --name build zmk-config build -b corne_min_left -s rgbled_adapter -a corne_min-left
          docker run --rm "${DOCKER_MOUNTS[@]}" --name build zmk-config build -b corne_min_right -s rgbled_adapter -a corne_min-right
          ;;
        ferris_sweep)
          docker run --rm "${DOCKER_MOUNTS[@]}" --name build zmk-config build -b nice_nano_v2 -s cradio_left -a ferris_sweep-left
          docker run --rm "${DOCKER_MOUNTS[@]}" --name build zmk-config build -b nice_nano_v2 -s cradio_right -a ferris_sweep-right
          ;;
      esac
    done

    open firmware
    ;;

  i) docker build --tag zmk-config . ;;
  s) docker run --rm "${DOCKER_MOUNTS[@]}" --name shell --entrypoint /bin/bash -it zmk-config ;;
esac
