#!/bin/bash

set -euo pipefail

DOCKER_OPTS=(
  --rm
  --mount type=bind,src=./config,dst=/workspaces/config,readonly
  --mount type=bind,src=./firmware,dst=/workspaces/firmware,bind-create-src
  --mount type=bind,src=./images,dst=/workspaces/images
)

mode="f"

while getopts "dfi" opt; do
  case ${opt} in
    *) mode=${opt} ;;
  esac
done

case ${mode} in
  d)
    docker run "${DOCKER_OPTS[@]}" zmk-config draw -k cradio
    open images/cradio.svg
    ;;

  f)
    docker run "${DOCKER_OPTS[@]}" zmk-config build -b nice_nano_v2 -s cradio_left
    docker run "${DOCKER_OPTS[@]}" zmk-config build -b nice_nano_v2 -s cradio_right
    open firmware
    ;;

  i)
    docker build --tag zmk-config .
    ;;
esac
