#!/bin/bash

set -euo pipefail

usage() {
  cat <<-END
usage: build [-I] firmware [-k <keyboard>]
       build [-I] keymap [-k <keyboard>]
       build [-I] shell

  global options:
    -I             build docker image

  commands:
    firmware       build keyboard firmware (default)
    keymap         draw keyboard keymap
    shell          start an interactive shell in the docker container

  options:
    -k <keyboard>  select keyboard

  keyboards:
    ferris_sweep (default)
    corne_min

END
}

docker_run() {
  build=$(mktemp -d -t zmk-config)

  if [ -z "${1+x}" ]; then
    local tty="--tty"
  fi

  docker run --interactive --rm ${tty:-} \
    --mount type=bind,src=./config,dst=/app/config,readonly \
    --mount type=bind,src=${build},dst=/app/build \
    zmk-config "$@"
}

west() {
  docker_run west "$@"
}

keymap() {
  docker_run keymap -c config/keymap-drawer.yml "$@"
}

while getopts "Ih" opt; do
  case ${opt} in
    I) docker build --tag zmk-config . ;;
    h) usage; exit 0 ;;
   \?) usage; exit 1 ;;
  esac
done

shift $((OPTIND-1))
command=${1:-default}
shift||
OPTIND=1

case ${command} in
  firmware|default)
    while getopts "k:h" opt; do
      case ${opt} in
        k) keyboard=${OPTARG} ;;
        h) usage; exit 0 ;;
       \?) usage; exit 1 ;;
      esac
    done

    mkdir -p firmware

    case ${keyboard:-default} in
      ferris_sweep|default)
        west build -s zmk/app -d /app/build -b nice_nano_v2 -- -DZMK_CONFIG=/app/config -DSHIELD=cradio_left
        cp ${build}/zephyr/zmk.uf2 firmware/ferris_sweep-left.uf2
        west build -s zmk/app -d /app/build -b nice_nano_v2 -- -DZMK_CONFIG=/app/config -DSHIELD=cradio_right
        cp ${build}/zephyr/zmk.uf2 firmware/ferris_sweep-right.uf2
        ;;
      corne_min)
        west build -s zmk/app -d /app/build -b corne_min_left -- -DZMK_CONFIG=/app/config -DSHIELD=rgbled_adapter
        cp ${build}/zephyr/zmk.uf2 firmware/corne_min-left.uf2
        west build -s zmk/app -d /app/build -b corne_min_right -- -DZMK_CONFIG=/app/config -DSHIELD=rgbled_adapter
        cp ${build}/zephyr/zmk.uf2 firmware/corne_min-right.uf2
        ;;
      *)
        echo "${0}: unrecognized keyboard -- ${keyboard}"
        usage
        exit 1
        ;;
    esac

    open firmware
    ;;

  keymap)
    while getopts "k:h" opt; do
      case ${opt} in
        k) keyboard=${OPTARG} ;;
        h) usage; exit 0 ;;
       \?) usage; exit 1 ;;
      esac
    done

    case ${keyboard:-default} in
      ferris_sweep|default)
        keymap parse -z config/cradio.keymap | keymap draw - > img/cradio.svg
        open img/cradio.svg
        ;;
      corne_min)
        keymap parse -z config/corne_min.keymap | keymap draw -d zmk/app/dts/layouts/foostan/corne/6column.dtsi - > img/corne_min.svg
        open img/corne_min.svg
        ;;
      *)
        echo "${0}: unrecognized keyboard -- ${keyboard}"
        usage
        exit 1
        ;;
    esac
    ;;

  shell)
    docker_run
    ;;

  *)
    echo "${0}: unrecognized command -- ${command}"
    usage
    exit 1
    ;;

esac
