manifest:
  remotes:
    - name: matthewtodd
      url-base: https://github.com/matthewtodd
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrproject.org/3.2.0/develop/west/manifest.html#projects
  projects:
    - name: zmk
      remote: matthewtodd
      revision: caps-word-deactivate-by-numeric-with-modifiers
      import: app/west.yml
  self:
    path: config
