on:
  push:
    paths:
      - "build.yaml"
      - "config/*"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: matthewtodd/zmk/.github/workflows/build-user-config.yml@caps-word-deactivate-by-numeric-with-modifiers
